### ISSUE TITLE
Incorrect most recent friday for live data predictions

### ISSUE THREAD

**Issue by ptlorenz** [sturlese/numerai_signals_pipeline#3]
This and last week the pipeline throws out the actual most recent fridays (2022-08-26, 2022-08-19) and pretends 2022-08-12 is the most recent friday. This of course causes the live data set to have 0 rows and thus no predictions.

It seems this happens in the ***FEATURE ENGINEERING... (or in the creating lags to indicators, or ***COMPRESSING ENGINEERED FEATURES FILES) part of the pipeline.
What could be the reason for this?

<img width="1012" alt="Screenshot 2022-08-28 at 19 06 48" src="https://user-images.githubusercontent.com/61086523/187232855-cd28964a-da10-4256-9e99-8852a9acd878.png">

**Comment by sturlese** [comment]
Did you change the flag 'skip_download'? (default is False)? If you did, you are not downloading the most recent yahoo snapshot on each execution. 
Another thing, at what time and timezone are you running it? This could also be the cause. If you run it, for example, Sunday 10:00am UTC+2, does the problem happen?

**Comment by ptlorenz** [comment]
Yes works during the right time. Thanks a lot!
Deeply appreciated helping out a noob!
